Desicion Tree!! -360DIGITMG

Decision Tree is a Supervised learning technique that can be used for both classification and Regression problems.
Decision Tree uses a flowchart like a tree structure to show the predictions that result from a series of feature-based splits. It starts with a root node and ends with a decision made by leaves.

Random Forest
A random forest is a machine learning technique that’s used to solve regression and classification problems. It utilizes ensemble learning, which is a technique that combines many classifiers to provide solutions to complex problems.

A random forest algorithm consists of many decision trees. The ‘forest’ generated by the random forest algorithm is trained through bagging or bootstrap aggregating.

Desicion Tree 4. In the recruitment domain, HR faces the challenge of predicting if the candidate is faking their salary or not. For example, a candidate claims to have 5 years of experience and earns 70,000 per month working as a regional manager. The candidate expects more money than his previous CTC. We need a way to verify their claims (is 70,000 a month working as a regional manager with an experience of 5 years a genuine claim or does he/she make less than that?) Build a Decision Tree and Random Forest model with monthly income as the target variable.

Business objective: predict whether the candidate is faking his salary or not based on experiance.

In [1]:
# Importing Fraud_check dataset using pandas
import pandas as pd
hr = pd.read_csv(r"C:\Users\D\Desktop\New Assignments  Keys\Datasets\HR_DT.csv")

In [2]:
hr.columns

Index(['Position of the employee', 'no of Years of Experience of employee',
       ' monthly income of employee'],
      dtype='object')

In [3]:
### EDA, Pre-processing
hr.info()
hr.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 196 entries, 0 to 195
Data columns (total 3 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Position of the employee               196 non-null    object
 1   no of Years of Experience of employee  196 non-null    float64
 2    monthly income of employee            196 non-null    int64
dtypes: float64(1), int64(1), object(1)
memory usage: 4.7+ KB

,Position of the employee,no of Years of Experience of employee,monthly income of employee
0,Business Analyst,1.1,39343
1,Junior Consultant,1.3,46205
2,Senior Consultant,1.5,37731
3,Manager,2.0,43525
4,Country Manager,2.2,39891

monthly income is the target variable which we have to predict

other 2 variables are predictore - no. of years is numerical

position is categorical which has to be converted to numeric

In [4]:
# Missing values
hr.isnull().sum()
# there are no missing values in our dataset

Position of the employee                 0
no of Years of Experience of employee    0
 monthly income of employee              0
dtype: int64

In [5]:
hr['Position of the employee'].value_counts(normalize = True)
# we see this is ordinal data so we can convert it to numerical position wise, higher position - higher number, lower position - lower number

Partner              0.142857
Senior Partner       0.127551
C-level              0.122449
Region Manager       0.117347
CEO                  0.117347
Country Manager      0.091837
Manager              0.086735
Senior Consultant    0.081633
Junior Consultant    0.071429
Business Analyst     0.040816
Name: Position of the employee, dtype: float64

In [6]:
position_label_mapping = {'Business Analyst': 1, 'Junior Consultant': 2, 'Senior Consultant': 3, 'Manager': 4, 'Country Manager': 5,'Region Manager': 6,
                          'Partner': 7, 'Senior Partner': 8, 'C-level': 9, 'CEO': 10}

hr['Position of the employee'] = hr['Position of the employee'].map(position_label_mapping)

In [7]:
# Input and Output Split
predictors = hr.iloc[:,:-1]
target = hr[" monthly income of employee"]

In [8]:
# Splitting data into training and testing data set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(predictors, target, test_size = 0.25, random_state=0)

In [9]:
from sklearn import tree
regtree = tree.DecisionTreeRegressor()
regtree.fit(x_train, y_train)

DecisionTreeRegressor()

In [10]:
# Prediction
test_pred = regtree.predict(x_test)
train_pred = regtree.predict(x_train)

In [11]:
# Measuring accuracy
from sklearn.metrics import mean_squared_error, r2_score
# Error on test dataset
mean_squared_error(y_test, test_pred)

9183171.173469387

In [12]:
r2_score(y_test, test_pred)
# we get Rsquare of 0.98 on test dataset which is very good

0.9874866988336867

In [13]:
# Error on train dataset
mean_squared_error(y_train, train_pred)

478606.6258503401

In [14]:
r2_score(y_train, train_pred)
# we get Rsquare of 0.999 which is almost 1 on train dataset

0.9993193955756063

In [15]:
# let us try Random forest
from sklearn.ensemble import RandomForestRegressor
rf_clf = RandomForestRegressor(n_estimators=500, n_jobs=1, random_state=42)
rf_clf.fit(x_train, y_train)

RandomForestRegressor(n_estimators=500, n_jobs=1, random_state=42)

In [16]:
# Error on test dataset
mean_squared_error(y_test, rf_clf.predict(x_test))

6186790.451892138

In [17]:
r2_score(y_test, rf_clf.predict(x_test))
# we see that our mean squared error goes down
# we also see that our R squared is now 99.15% which has increased
# we will therefore use this model generated by using RandomForrest

0.9915696690484155

In [18]:
# let us now check if candidate is honest or fraud
# first we will have to add his entry to our x_test data
cand = {'Position of the employee': 6, 'no of Years of Experience of employee': 5.0}
x_test_cand = x_test.append(cand, ignore_index = True)
x_test_preds = rf_clf.predict(x_test_cand)
# since it was the last row that we added, we are only interested in predicted value of the last row

In [19]:
x_test_preds[-1]
# we get a value of 67802.17

67802.17

According to our model the candidate appears to be faking his salary

since the model predicts his salary to be less than 70000.